
language: node_js

node_js:
 - stable

branches:
  only:
  - master

before_install:
  - npm config set registry=https://registry.npm.taobao.org/

script:
 - npm run build

 notifications:
  email:
    recipients:
      - 15927700473@163.com
    on_success: never # default: change
    on_failure: always # default: always